Update main.py
  File "/Users/japr/Documents/python_proyectos/flet_ejemplos/dt_flex.py", line 327, in main
    table.fill_data_table()
  File "/Users/japr/Documents/python_proyectos/flet_ejemplos/dt_flex.py", line 290, in fill_data_table
    data = ft.DataRow()
           ^^^^^^^^^^^^
TypeError: DataRow.__init__() missing 1 required positional argument: 'cells'